version: '3'
services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    container_name: ms
    hostname: ms
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    links:
      - db
    depends_on:
      - db
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4
    networks:
      - metasploit
    command: ["./wait-for-postgres.sh", "db", "./msfconsole", "-r docker/msfconsole.rc"]

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    networks:
      - metasploit
    volumes:
      - './../pentest_data:/var/lib/postgresql/data'
networks:
  metasploit:
    driver: bridge